import type { Language } from '@devvault/shared';

export const LANGUAGE_LABELS: Record<Language, string> = {
  text: 'Plain text',
  bash: 'Bash / Shell',
  powershell: 'PowerShell',
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  jsx: 'JSX',
  tsx: 'TSX',
  json: 'JSON',
  python: 'Python',
  sql: 'SQL',
  go: 'Go',
  rust: 'Rust',
  java: 'Java',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  php: 'PHP',
  ruby: 'Ruby',
  html: 'HTML',
  css: 'CSS',
  yaml: 'YAML',
  toml: 'TOML',
  ini: 'INI / .env',
  dockerfile: 'Dockerfile',
  nginx: 'Nginx',
  graphql: 'GraphQL',
  markdown: 'Markdown',
  diff: 'Diff',
};
